// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Service.proto

#include "Service.pb.h"
#include "Service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace ProtoStruct {

static const char* ProtoService_method_names[] = {
  "/ProtoStruct.ProtoService/Enc",
  "/ProtoStruct.ProtoService/EncData",
  "/ProtoStruct.ProtoService/DecData",
  "/ProtoStruct.ProtoService/GetPP",
  "/ProtoStruct.ProtoService/GetUSK",
  "/ProtoStruct.ProtoService/SetPP",
  "/ProtoStruct.ProtoService/SetUSK",
};

std::unique_ptr< ProtoService::Stub> ProtoService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ProtoService::Stub> stub(new ProtoService::Stub(channel, options));
  return stub;
}

ProtoService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Enc_(ProtoService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_EncData_(ProtoService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DecData_(ProtoService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetPP_(ProtoService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetUSK_(ProtoService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetPP_(ProtoService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetUSK_(ProtoService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ProtoService::Stub::Enc(::grpc::ClientContext* context, const ::ProtoStruct::Element& request, ::ProtoStruct::Element* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ProtoStruct::Element, ::ProtoStruct::Element, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Enc_, context, request, response);
}

void ProtoService::Stub::async::Enc(::grpc::ClientContext* context, const ::ProtoStruct::Element* request, ::ProtoStruct::Element* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ProtoStruct::Element, ::ProtoStruct::Element, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Enc_, context, request, response, std::move(f));
}

void ProtoService::Stub::async::Enc(::grpc::ClientContext* context, const ::ProtoStruct::Element* request, ::ProtoStruct::Element* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Enc_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ProtoStruct::Element>* ProtoService::Stub::PrepareAsyncEncRaw(::grpc::ClientContext* context, const ::ProtoStruct::Element& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ProtoStruct::Element, ::ProtoStruct::Element, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Enc_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ProtoStruct::Element>* ProtoService::Stub::AsyncEncRaw(::grpc::ClientContext* context, const ::ProtoStruct::Element& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncEncRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ProtoService::Stub::EncData(::grpc::ClientContext* context, const ::ProtoStruct::DataMessage& request, ::ProtoStruct::CTMessage* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ProtoStruct::DataMessage, ::ProtoStruct::CTMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_EncData_, context, request, response);
}

void ProtoService::Stub::async::EncData(::grpc::ClientContext* context, const ::ProtoStruct::DataMessage* request, ::ProtoStruct::CTMessage* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ProtoStruct::DataMessage, ::ProtoStruct::CTMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_EncData_, context, request, response, std::move(f));
}

void ProtoService::Stub::async::EncData(::grpc::ClientContext* context, const ::ProtoStruct::DataMessage* request, ::ProtoStruct::CTMessage* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_EncData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ProtoStruct::CTMessage>* ProtoService::Stub::PrepareAsyncEncDataRaw(::grpc::ClientContext* context, const ::ProtoStruct::DataMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ProtoStruct::CTMessage, ::ProtoStruct::DataMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_EncData_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ProtoStruct::CTMessage>* ProtoService::Stub::AsyncEncDataRaw(::grpc::ClientContext* context, const ::ProtoStruct::DataMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncEncDataRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ProtoService::Stub::DecData(::grpc::ClientContext* context, const ::ProtoStruct::CTMessage& request, ::ProtoStruct::DataMessage* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ProtoStruct::CTMessage, ::ProtoStruct::DataMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DecData_, context, request, response);
}

void ProtoService::Stub::async::DecData(::grpc::ClientContext* context, const ::ProtoStruct::CTMessage* request, ::ProtoStruct::DataMessage* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ProtoStruct::CTMessage, ::ProtoStruct::DataMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DecData_, context, request, response, std::move(f));
}

void ProtoService::Stub::async::DecData(::grpc::ClientContext* context, const ::ProtoStruct::CTMessage* request, ::ProtoStruct::DataMessage* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DecData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ProtoStruct::DataMessage>* ProtoService::Stub::PrepareAsyncDecDataRaw(::grpc::ClientContext* context, const ::ProtoStruct::CTMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ProtoStruct::DataMessage, ::ProtoStruct::CTMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DecData_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ProtoStruct::DataMessage>* ProtoService::Stub::AsyncDecDataRaw(::grpc::ClientContext* context, const ::ProtoStruct::CTMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDecDataRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ProtoService::Stub::GetPP(::grpc::ClientContext* context, const ::ProtoStruct::EmptyMessage& request, ::ProtoStruct::PPMessage* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ProtoStruct::EmptyMessage, ::ProtoStruct::PPMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetPP_, context, request, response);
}

void ProtoService::Stub::async::GetPP(::grpc::ClientContext* context, const ::ProtoStruct::EmptyMessage* request, ::ProtoStruct::PPMessage* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ProtoStruct::EmptyMessage, ::ProtoStruct::PPMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPP_, context, request, response, std::move(f));
}

void ProtoService::Stub::async::GetPP(::grpc::ClientContext* context, const ::ProtoStruct::EmptyMessage* request, ::ProtoStruct::PPMessage* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPP_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ProtoStruct::PPMessage>* ProtoService::Stub::PrepareAsyncGetPPRaw(::grpc::ClientContext* context, const ::ProtoStruct::EmptyMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ProtoStruct::PPMessage, ::ProtoStruct::EmptyMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetPP_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ProtoStruct::PPMessage>* ProtoService::Stub::AsyncGetPPRaw(::grpc::ClientContext* context, const ::ProtoStruct::EmptyMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetPPRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ProtoService::Stub::GetUSK(::grpc::ClientContext* context, const ::ProtoStruct::AttributeMessage& request, ::ProtoStruct::USKMessage* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ProtoStruct::AttributeMessage, ::ProtoStruct::USKMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetUSK_, context, request, response);
}

void ProtoService::Stub::async::GetUSK(::grpc::ClientContext* context, const ::ProtoStruct::AttributeMessage* request, ::ProtoStruct::USKMessage* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ProtoStruct::AttributeMessage, ::ProtoStruct::USKMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetUSK_, context, request, response, std::move(f));
}

void ProtoService::Stub::async::GetUSK(::grpc::ClientContext* context, const ::ProtoStruct::AttributeMessage* request, ::ProtoStruct::USKMessage* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetUSK_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ProtoStruct::USKMessage>* ProtoService::Stub::PrepareAsyncGetUSKRaw(::grpc::ClientContext* context, const ::ProtoStruct::AttributeMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ProtoStruct::USKMessage, ::ProtoStruct::AttributeMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetUSK_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ProtoStruct::USKMessage>* ProtoService::Stub::AsyncGetUSKRaw(::grpc::ClientContext* context, const ::ProtoStruct::AttributeMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetUSKRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ProtoService::Stub::SetPP(::grpc::ClientContext* context, const ::ProtoStruct::PPMessage& request, ::ProtoStruct::EmptyMessage* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ProtoStruct::PPMessage, ::ProtoStruct::EmptyMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetPP_, context, request, response);
}

void ProtoService::Stub::async::SetPP(::grpc::ClientContext* context, const ::ProtoStruct::PPMessage* request, ::ProtoStruct::EmptyMessage* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ProtoStruct::PPMessage, ::ProtoStruct::EmptyMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetPP_, context, request, response, std::move(f));
}

void ProtoService::Stub::async::SetPP(::grpc::ClientContext* context, const ::ProtoStruct::PPMessage* request, ::ProtoStruct::EmptyMessage* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetPP_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ProtoStruct::EmptyMessage>* ProtoService::Stub::PrepareAsyncSetPPRaw(::grpc::ClientContext* context, const ::ProtoStruct::PPMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ProtoStruct::EmptyMessage, ::ProtoStruct::PPMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetPP_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ProtoStruct::EmptyMessage>* ProtoService::Stub::AsyncSetPPRaw(::grpc::ClientContext* context, const ::ProtoStruct::PPMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetPPRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ProtoService::Stub::SetUSK(::grpc::ClientContext* context, const ::ProtoStruct::USKMessage& request, ::ProtoStruct::EmptyMessage* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ProtoStruct::USKMessage, ::ProtoStruct::EmptyMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetUSK_, context, request, response);
}

void ProtoService::Stub::async::SetUSK(::grpc::ClientContext* context, const ::ProtoStruct::USKMessage* request, ::ProtoStruct::EmptyMessage* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ProtoStruct::USKMessage, ::ProtoStruct::EmptyMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetUSK_, context, request, response, std::move(f));
}

void ProtoService::Stub::async::SetUSK(::grpc::ClientContext* context, const ::ProtoStruct::USKMessage* request, ::ProtoStruct::EmptyMessage* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetUSK_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ProtoStruct::EmptyMessage>* ProtoService::Stub::PrepareAsyncSetUSKRaw(::grpc::ClientContext* context, const ::ProtoStruct::USKMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ProtoStruct::EmptyMessage, ::ProtoStruct::USKMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetUSK_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ProtoStruct::EmptyMessage>* ProtoService::Stub::AsyncSetUSKRaw(::grpc::ClientContext* context, const ::ProtoStruct::USKMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetUSKRaw(context, request, cq);
  result->StartCall();
  return result;
}

ProtoService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ProtoService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ProtoService::Service, ::ProtoStruct::Element, ::ProtoStruct::Element, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ProtoService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ProtoStruct::Element* req,
             ::ProtoStruct::Element* resp) {
               return service->Enc(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ProtoService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ProtoService::Service, ::ProtoStruct::DataMessage, ::ProtoStruct::CTMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ProtoService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ProtoStruct::DataMessage* req,
             ::ProtoStruct::CTMessage* resp) {
               return service->EncData(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ProtoService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ProtoService::Service, ::ProtoStruct::CTMessage, ::ProtoStruct::DataMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ProtoService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ProtoStruct::CTMessage* req,
             ::ProtoStruct::DataMessage* resp) {
               return service->DecData(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ProtoService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ProtoService::Service, ::ProtoStruct::EmptyMessage, ::ProtoStruct::PPMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ProtoService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ProtoStruct::EmptyMessage* req,
             ::ProtoStruct::PPMessage* resp) {
               return service->GetPP(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ProtoService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ProtoService::Service, ::ProtoStruct::AttributeMessage, ::ProtoStruct::USKMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ProtoService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ProtoStruct::AttributeMessage* req,
             ::ProtoStruct::USKMessage* resp) {
               return service->GetUSK(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ProtoService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ProtoService::Service, ::ProtoStruct::PPMessage, ::ProtoStruct::EmptyMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ProtoService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ProtoStruct::PPMessage* req,
             ::ProtoStruct::EmptyMessage* resp) {
               return service->SetPP(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ProtoService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ProtoService::Service, ::ProtoStruct::USKMessage, ::ProtoStruct::EmptyMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ProtoService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ProtoStruct::USKMessage* req,
             ::ProtoStruct::EmptyMessage* resp) {
               return service->SetUSK(ctx, req, resp);
             }, this)));
}

ProtoService::Service::~Service() {
}

::grpc::Status ProtoService::Service::Enc(::grpc::ServerContext* context, const ::ProtoStruct::Element* request, ::ProtoStruct::Element* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ProtoService::Service::EncData(::grpc::ServerContext* context, const ::ProtoStruct::DataMessage* request, ::ProtoStruct::CTMessage* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ProtoService::Service::DecData(::grpc::ServerContext* context, const ::ProtoStruct::CTMessage* request, ::ProtoStruct::DataMessage* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ProtoService::Service::GetPP(::grpc::ServerContext* context, const ::ProtoStruct::EmptyMessage* request, ::ProtoStruct::PPMessage* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ProtoService::Service::GetUSK(::grpc::ServerContext* context, const ::ProtoStruct::AttributeMessage* request, ::ProtoStruct::USKMessage* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ProtoService::Service::SetPP(::grpc::ServerContext* context, const ::ProtoStruct::PPMessage* request, ::ProtoStruct::EmptyMessage* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ProtoService::Service::SetUSK(::grpc::ServerContext* context, const ::ProtoStruct::USKMessage* request, ::ProtoStruct::EmptyMessage* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ProtoStruct
#include <grpcpp/ports_undef.inc>

