// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Service.proto
#ifndef GRPC_Service_2eproto__INCLUDED
#define GRPC_Service_2eproto__INCLUDED

#include "Service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace ProtoStruct {

class ProtoService final {
 public:
  static constexpr char const* service_full_name() {
    return "ProtoStruct.ProtoService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Enc(::grpc::ClientContext* context, const ::ProtoStruct::Element& request, ::ProtoStruct::Element* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::Element>> AsyncEnc(::grpc::ClientContext* context, const ::ProtoStruct::Element& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::Element>>(AsyncEncRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::Element>> PrepareAsyncEnc(::grpc::ClientContext* context, const ::ProtoStruct::Element& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::Element>>(PrepareAsyncEncRaw(context, request, cq));
    }
    virtual ::grpc::Status EncData(::grpc::ClientContext* context, const ::ProtoStruct::DataMessage& request, ::ProtoStruct::CTMessage* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::CTMessage>> AsyncEncData(::grpc::ClientContext* context, const ::ProtoStruct::DataMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::CTMessage>>(AsyncEncDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::CTMessage>> PrepareAsyncEncData(::grpc::ClientContext* context, const ::ProtoStruct::DataMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::CTMessage>>(PrepareAsyncEncDataRaw(context, request, cq));
    }
    virtual ::grpc::Status DecData(::grpc::ClientContext* context, const ::ProtoStruct::CTMessage& request, ::ProtoStruct::DataMessage* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::DataMessage>> AsyncDecData(::grpc::ClientContext* context, const ::ProtoStruct::CTMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::DataMessage>>(AsyncDecDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::DataMessage>> PrepareAsyncDecData(::grpc::ClientContext* context, const ::ProtoStruct::CTMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::DataMessage>>(PrepareAsyncDecDataRaw(context, request, cq));
    }
    virtual ::grpc::Status GetPP(::grpc::ClientContext* context, const ::ProtoStruct::EmptyMessage& request, ::ProtoStruct::PPMessage* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::PPMessage>> AsyncGetPP(::grpc::ClientContext* context, const ::ProtoStruct::EmptyMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::PPMessage>>(AsyncGetPPRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::PPMessage>> PrepareAsyncGetPP(::grpc::ClientContext* context, const ::ProtoStruct::EmptyMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::PPMessage>>(PrepareAsyncGetPPRaw(context, request, cq));
    }
    virtual ::grpc::Status GetUSK(::grpc::ClientContext* context, const ::ProtoStruct::AttributeMessage& request, ::ProtoStruct::USKMessage* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::USKMessage>> AsyncGetUSK(::grpc::ClientContext* context, const ::ProtoStruct::AttributeMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::USKMessage>>(AsyncGetUSKRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::USKMessage>> PrepareAsyncGetUSK(::grpc::ClientContext* context, const ::ProtoStruct::AttributeMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::USKMessage>>(PrepareAsyncGetUSKRaw(context, request, cq));
    }
    virtual ::grpc::Status SetPP(::grpc::ClientContext* context, const ::ProtoStruct::PPMessage& request, ::ProtoStruct::EmptyMessage* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::EmptyMessage>> AsyncSetPP(::grpc::ClientContext* context, const ::ProtoStruct::PPMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::EmptyMessage>>(AsyncSetPPRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::EmptyMessage>> PrepareAsyncSetPP(::grpc::ClientContext* context, const ::ProtoStruct::PPMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::EmptyMessage>>(PrepareAsyncSetPPRaw(context, request, cq));
    }
    virtual ::grpc::Status SetUSK(::grpc::ClientContext* context, const ::ProtoStruct::USKMessage& request, ::ProtoStruct::EmptyMessage* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::EmptyMessage>> AsyncSetUSK(::grpc::ClientContext* context, const ::ProtoStruct::USKMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::EmptyMessage>>(AsyncSetUSKRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::EmptyMessage>> PrepareAsyncSetUSK(::grpc::ClientContext* context, const ::ProtoStruct::USKMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::EmptyMessage>>(PrepareAsyncSetUSKRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Enc(::grpc::ClientContext* context, const ::ProtoStruct::Element* request, ::ProtoStruct::Element* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Enc(::grpc::ClientContext* context, const ::ProtoStruct::Element* request, ::ProtoStruct::Element* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void EncData(::grpc::ClientContext* context, const ::ProtoStruct::DataMessage* request, ::ProtoStruct::CTMessage* response, std::function<void(::grpc::Status)>) = 0;
      virtual void EncData(::grpc::ClientContext* context, const ::ProtoStruct::DataMessage* request, ::ProtoStruct::CTMessage* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void DecData(::grpc::ClientContext* context, const ::ProtoStruct::CTMessage* request, ::ProtoStruct::DataMessage* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DecData(::grpc::ClientContext* context, const ::ProtoStruct::CTMessage* request, ::ProtoStruct::DataMessage* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetPP(::grpc::ClientContext* context, const ::ProtoStruct::EmptyMessage* request, ::ProtoStruct::PPMessage* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetPP(::grpc::ClientContext* context, const ::ProtoStruct::EmptyMessage* request, ::ProtoStruct::PPMessage* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetUSK(::grpc::ClientContext* context, const ::ProtoStruct::AttributeMessage* request, ::ProtoStruct::USKMessage* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetUSK(::grpc::ClientContext* context, const ::ProtoStruct::AttributeMessage* request, ::ProtoStruct::USKMessage* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void SetPP(::grpc::ClientContext* context, const ::ProtoStruct::PPMessage* request, ::ProtoStruct::EmptyMessage* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetPP(::grpc::ClientContext* context, const ::ProtoStruct::PPMessage* request, ::ProtoStruct::EmptyMessage* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void SetUSK(::grpc::ClientContext* context, const ::ProtoStruct::USKMessage* request, ::ProtoStruct::EmptyMessage* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetUSK(::grpc::ClientContext* context, const ::ProtoStruct::USKMessage* request, ::ProtoStruct::EmptyMessage* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::Element>* AsyncEncRaw(::grpc::ClientContext* context, const ::ProtoStruct::Element& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::Element>* PrepareAsyncEncRaw(::grpc::ClientContext* context, const ::ProtoStruct::Element& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::CTMessage>* AsyncEncDataRaw(::grpc::ClientContext* context, const ::ProtoStruct::DataMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::CTMessage>* PrepareAsyncEncDataRaw(::grpc::ClientContext* context, const ::ProtoStruct::DataMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::DataMessage>* AsyncDecDataRaw(::grpc::ClientContext* context, const ::ProtoStruct::CTMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::DataMessage>* PrepareAsyncDecDataRaw(::grpc::ClientContext* context, const ::ProtoStruct::CTMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::PPMessage>* AsyncGetPPRaw(::grpc::ClientContext* context, const ::ProtoStruct::EmptyMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::PPMessage>* PrepareAsyncGetPPRaw(::grpc::ClientContext* context, const ::ProtoStruct::EmptyMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::USKMessage>* AsyncGetUSKRaw(::grpc::ClientContext* context, const ::ProtoStruct::AttributeMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::USKMessage>* PrepareAsyncGetUSKRaw(::grpc::ClientContext* context, const ::ProtoStruct::AttributeMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::EmptyMessage>* AsyncSetPPRaw(::grpc::ClientContext* context, const ::ProtoStruct::PPMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::EmptyMessage>* PrepareAsyncSetPPRaw(::grpc::ClientContext* context, const ::ProtoStruct::PPMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::EmptyMessage>* AsyncSetUSKRaw(::grpc::ClientContext* context, const ::ProtoStruct::USKMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ProtoStruct::EmptyMessage>* PrepareAsyncSetUSKRaw(::grpc::ClientContext* context, const ::ProtoStruct::USKMessage& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Enc(::grpc::ClientContext* context, const ::ProtoStruct::Element& request, ::ProtoStruct::Element* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::Element>> AsyncEnc(::grpc::ClientContext* context, const ::ProtoStruct::Element& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::Element>>(AsyncEncRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::Element>> PrepareAsyncEnc(::grpc::ClientContext* context, const ::ProtoStruct::Element& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::Element>>(PrepareAsyncEncRaw(context, request, cq));
    }
    ::grpc::Status EncData(::grpc::ClientContext* context, const ::ProtoStruct::DataMessage& request, ::ProtoStruct::CTMessage* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::CTMessage>> AsyncEncData(::grpc::ClientContext* context, const ::ProtoStruct::DataMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::CTMessage>>(AsyncEncDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::CTMessage>> PrepareAsyncEncData(::grpc::ClientContext* context, const ::ProtoStruct::DataMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::CTMessage>>(PrepareAsyncEncDataRaw(context, request, cq));
    }
    ::grpc::Status DecData(::grpc::ClientContext* context, const ::ProtoStruct::CTMessage& request, ::ProtoStruct::DataMessage* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::DataMessage>> AsyncDecData(::grpc::ClientContext* context, const ::ProtoStruct::CTMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::DataMessage>>(AsyncDecDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::DataMessage>> PrepareAsyncDecData(::grpc::ClientContext* context, const ::ProtoStruct::CTMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::DataMessage>>(PrepareAsyncDecDataRaw(context, request, cq));
    }
    ::grpc::Status GetPP(::grpc::ClientContext* context, const ::ProtoStruct::EmptyMessage& request, ::ProtoStruct::PPMessage* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::PPMessage>> AsyncGetPP(::grpc::ClientContext* context, const ::ProtoStruct::EmptyMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::PPMessage>>(AsyncGetPPRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::PPMessage>> PrepareAsyncGetPP(::grpc::ClientContext* context, const ::ProtoStruct::EmptyMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::PPMessage>>(PrepareAsyncGetPPRaw(context, request, cq));
    }
    ::grpc::Status GetUSK(::grpc::ClientContext* context, const ::ProtoStruct::AttributeMessage& request, ::ProtoStruct::USKMessage* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::USKMessage>> AsyncGetUSK(::grpc::ClientContext* context, const ::ProtoStruct::AttributeMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::USKMessage>>(AsyncGetUSKRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::USKMessage>> PrepareAsyncGetUSK(::grpc::ClientContext* context, const ::ProtoStruct::AttributeMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::USKMessage>>(PrepareAsyncGetUSKRaw(context, request, cq));
    }
    ::grpc::Status SetPP(::grpc::ClientContext* context, const ::ProtoStruct::PPMessage& request, ::ProtoStruct::EmptyMessage* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::EmptyMessage>> AsyncSetPP(::grpc::ClientContext* context, const ::ProtoStruct::PPMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::EmptyMessage>>(AsyncSetPPRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::EmptyMessage>> PrepareAsyncSetPP(::grpc::ClientContext* context, const ::ProtoStruct::PPMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::EmptyMessage>>(PrepareAsyncSetPPRaw(context, request, cq));
    }
    ::grpc::Status SetUSK(::grpc::ClientContext* context, const ::ProtoStruct::USKMessage& request, ::ProtoStruct::EmptyMessage* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::EmptyMessage>> AsyncSetUSK(::grpc::ClientContext* context, const ::ProtoStruct::USKMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::EmptyMessage>>(AsyncSetUSKRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::EmptyMessage>> PrepareAsyncSetUSK(::grpc::ClientContext* context, const ::ProtoStruct::USKMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ProtoStruct::EmptyMessage>>(PrepareAsyncSetUSKRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Enc(::grpc::ClientContext* context, const ::ProtoStruct::Element* request, ::ProtoStruct::Element* response, std::function<void(::grpc::Status)>) override;
      void Enc(::grpc::ClientContext* context, const ::ProtoStruct::Element* request, ::ProtoStruct::Element* response, ::grpc::ClientUnaryReactor* reactor) override;
      void EncData(::grpc::ClientContext* context, const ::ProtoStruct::DataMessage* request, ::ProtoStruct::CTMessage* response, std::function<void(::grpc::Status)>) override;
      void EncData(::grpc::ClientContext* context, const ::ProtoStruct::DataMessage* request, ::ProtoStruct::CTMessage* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DecData(::grpc::ClientContext* context, const ::ProtoStruct::CTMessage* request, ::ProtoStruct::DataMessage* response, std::function<void(::grpc::Status)>) override;
      void DecData(::grpc::ClientContext* context, const ::ProtoStruct::CTMessage* request, ::ProtoStruct::DataMessage* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetPP(::grpc::ClientContext* context, const ::ProtoStruct::EmptyMessage* request, ::ProtoStruct::PPMessage* response, std::function<void(::grpc::Status)>) override;
      void GetPP(::grpc::ClientContext* context, const ::ProtoStruct::EmptyMessage* request, ::ProtoStruct::PPMessage* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetUSK(::grpc::ClientContext* context, const ::ProtoStruct::AttributeMessage* request, ::ProtoStruct::USKMessage* response, std::function<void(::grpc::Status)>) override;
      void GetUSK(::grpc::ClientContext* context, const ::ProtoStruct::AttributeMessage* request, ::ProtoStruct::USKMessage* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SetPP(::grpc::ClientContext* context, const ::ProtoStruct::PPMessage* request, ::ProtoStruct::EmptyMessage* response, std::function<void(::grpc::Status)>) override;
      void SetPP(::grpc::ClientContext* context, const ::ProtoStruct::PPMessage* request, ::ProtoStruct::EmptyMessage* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SetUSK(::grpc::ClientContext* context, const ::ProtoStruct::USKMessage* request, ::ProtoStruct::EmptyMessage* response, std::function<void(::grpc::Status)>) override;
      void SetUSK(::grpc::ClientContext* context, const ::ProtoStruct::USKMessage* request, ::ProtoStruct::EmptyMessage* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ProtoStruct::Element>* AsyncEncRaw(::grpc::ClientContext* context, const ::ProtoStruct::Element& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ProtoStruct::Element>* PrepareAsyncEncRaw(::grpc::ClientContext* context, const ::ProtoStruct::Element& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ProtoStruct::CTMessage>* AsyncEncDataRaw(::grpc::ClientContext* context, const ::ProtoStruct::DataMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ProtoStruct::CTMessage>* PrepareAsyncEncDataRaw(::grpc::ClientContext* context, const ::ProtoStruct::DataMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ProtoStruct::DataMessage>* AsyncDecDataRaw(::grpc::ClientContext* context, const ::ProtoStruct::CTMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ProtoStruct::DataMessage>* PrepareAsyncDecDataRaw(::grpc::ClientContext* context, const ::ProtoStruct::CTMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ProtoStruct::PPMessage>* AsyncGetPPRaw(::grpc::ClientContext* context, const ::ProtoStruct::EmptyMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ProtoStruct::PPMessage>* PrepareAsyncGetPPRaw(::grpc::ClientContext* context, const ::ProtoStruct::EmptyMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ProtoStruct::USKMessage>* AsyncGetUSKRaw(::grpc::ClientContext* context, const ::ProtoStruct::AttributeMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ProtoStruct::USKMessage>* PrepareAsyncGetUSKRaw(::grpc::ClientContext* context, const ::ProtoStruct::AttributeMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ProtoStruct::EmptyMessage>* AsyncSetPPRaw(::grpc::ClientContext* context, const ::ProtoStruct::PPMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ProtoStruct::EmptyMessage>* PrepareAsyncSetPPRaw(::grpc::ClientContext* context, const ::ProtoStruct::PPMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ProtoStruct::EmptyMessage>* AsyncSetUSKRaw(::grpc::ClientContext* context, const ::ProtoStruct::USKMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ProtoStruct::EmptyMessage>* PrepareAsyncSetUSKRaw(::grpc::ClientContext* context, const ::ProtoStruct::USKMessage& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Enc_;
    const ::grpc::internal::RpcMethod rpcmethod_EncData_;
    const ::grpc::internal::RpcMethod rpcmethod_DecData_;
    const ::grpc::internal::RpcMethod rpcmethod_GetPP_;
    const ::grpc::internal::RpcMethod rpcmethod_GetUSK_;
    const ::grpc::internal::RpcMethod rpcmethod_SetPP_;
    const ::grpc::internal::RpcMethod rpcmethod_SetUSK_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Enc(::grpc::ServerContext* context, const ::ProtoStruct::Element* request, ::ProtoStruct::Element* response);
    virtual ::grpc::Status EncData(::grpc::ServerContext* context, const ::ProtoStruct::DataMessage* request, ::ProtoStruct::CTMessage* response);
    virtual ::grpc::Status DecData(::grpc::ServerContext* context, const ::ProtoStruct::CTMessage* request, ::ProtoStruct::DataMessage* response);
    virtual ::grpc::Status GetPP(::grpc::ServerContext* context, const ::ProtoStruct::EmptyMessage* request, ::ProtoStruct::PPMessage* response);
    virtual ::grpc::Status GetUSK(::grpc::ServerContext* context, const ::ProtoStruct::AttributeMessage* request, ::ProtoStruct::USKMessage* response);
    virtual ::grpc::Status SetPP(::grpc::ServerContext* context, const ::ProtoStruct::PPMessage* request, ::ProtoStruct::EmptyMessage* response);
    virtual ::grpc::Status SetUSK(::grpc::ServerContext* context, const ::ProtoStruct::USKMessage* request, ::ProtoStruct::EmptyMessage* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Enc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Enc() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Enc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Enc(::grpc::ServerContext* /*context*/, const ::ProtoStruct::Element* /*request*/, ::ProtoStruct::Element* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEnc(::grpc::ServerContext* context, ::ProtoStruct::Element* request, ::grpc::ServerAsyncResponseWriter< ::ProtoStruct::Element>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_EncData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_EncData() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_EncData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EncData(::grpc::ServerContext* /*context*/, const ::ProtoStruct::DataMessage* /*request*/, ::ProtoStruct::CTMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEncData(::grpc::ServerContext* context, ::ProtoStruct::DataMessage* request, ::grpc::ServerAsyncResponseWriter< ::ProtoStruct::CTMessage>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DecData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DecData() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_DecData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DecData(::grpc::ServerContext* /*context*/, const ::ProtoStruct::CTMessage* /*request*/, ::ProtoStruct::DataMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDecData(::grpc::ServerContext* context, ::ProtoStruct::CTMessage* request, ::grpc::ServerAsyncResponseWriter< ::ProtoStruct::DataMessage>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetPP : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetPP() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_GetPP() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPP(::grpc::ServerContext* /*context*/, const ::ProtoStruct::EmptyMessage* /*request*/, ::ProtoStruct::PPMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPP(::grpc::ServerContext* context, ::ProtoStruct::EmptyMessage* request, ::grpc::ServerAsyncResponseWriter< ::ProtoStruct::PPMessage>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetUSK : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetUSK() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_GetUSK() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUSK(::grpc::ServerContext* /*context*/, const ::ProtoStruct::AttributeMessage* /*request*/, ::ProtoStruct::USKMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetUSK(::grpc::ServerContext* context, ::ProtoStruct::AttributeMessage* request, ::grpc::ServerAsyncResponseWriter< ::ProtoStruct::USKMessage>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SetPP : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetPP() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_SetPP() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetPP(::grpc::ServerContext* /*context*/, const ::ProtoStruct::PPMessage* /*request*/, ::ProtoStruct::EmptyMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetPP(::grpc::ServerContext* context, ::ProtoStruct::PPMessage* request, ::grpc::ServerAsyncResponseWriter< ::ProtoStruct::EmptyMessage>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SetUSK : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetUSK() {
      ::grpc::Service::MarkMethodAsync(6);
    }
    ~WithAsyncMethod_SetUSK() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetUSK(::grpc::ServerContext* /*context*/, const ::ProtoStruct::USKMessage* /*request*/, ::ProtoStruct::EmptyMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetUSK(::grpc::ServerContext* context, ::ProtoStruct::USKMessage* request, ::grpc::ServerAsyncResponseWriter< ::ProtoStruct::EmptyMessage>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Enc<WithAsyncMethod_EncData<WithAsyncMethod_DecData<WithAsyncMethod_GetPP<WithAsyncMethod_GetUSK<WithAsyncMethod_SetPP<WithAsyncMethod_SetUSK<Service > > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Enc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Enc() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ProtoStruct::Element, ::ProtoStruct::Element>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ProtoStruct::Element* request, ::ProtoStruct::Element* response) { return this->Enc(context, request, response); }));}
    void SetMessageAllocatorFor_Enc(
        ::grpc::MessageAllocator< ::ProtoStruct::Element, ::ProtoStruct::Element>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ProtoStruct::Element, ::ProtoStruct::Element>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Enc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Enc(::grpc::ServerContext* /*context*/, const ::ProtoStruct::Element* /*request*/, ::ProtoStruct::Element* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Enc(
      ::grpc::CallbackServerContext* /*context*/, const ::ProtoStruct::Element* /*request*/, ::ProtoStruct::Element* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_EncData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_EncData() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::ProtoStruct::DataMessage, ::ProtoStruct::CTMessage>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ProtoStruct::DataMessage* request, ::ProtoStruct::CTMessage* response) { return this->EncData(context, request, response); }));}
    void SetMessageAllocatorFor_EncData(
        ::grpc::MessageAllocator< ::ProtoStruct::DataMessage, ::ProtoStruct::CTMessage>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ProtoStruct::DataMessage, ::ProtoStruct::CTMessage>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_EncData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EncData(::grpc::ServerContext* /*context*/, const ::ProtoStruct::DataMessage* /*request*/, ::ProtoStruct::CTMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* EncData(
      ::grpc::CallbackServerContext* /*context*/, const ::ProtoStruct::DataMessage* /*request*/, ::ProtoStruct::CTMessage* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DecData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DecData() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::ProtoStruct::CTMessage, ::ProtoStruct::DataMessage>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ProtoStruct::CTMessage* request, ::ProtoStruct::DataMessage* response) { return this->DecData(context, request, response); }));}
    void SetMessageAllocatorFor_DecData(
        ::grpc::MessageAllocator< ::ProtoStruct::CTMessage, ::ProtoStruct::DataMessage>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ProtoStruct::CTMessage, ::ProtoStruct::DataMessage>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DecData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DecData(::grpc::ServerContext* /*context*/, const ::ProtoStruct::CTMessage* /*request*/, ::ProtoStruct::DataMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DecData(
      ::grpc::CallbackServerContext* /*context*/, const ::ProtoStruct::CTMessage* /*request*/, ::ProtoStruct::DataMessage* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetPP : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetPP() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::ProtoStruct::EmptyMessage, ::ProtoStruct::PPMessage>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ProtoStruct::EmptyMessage* request, ::ProtoStruct::PPMessage* response) { return this->GetPP(context, request, response); }));}
    void SetMessageAllocatorFor_GetPP(
        ::grpc::MessageAllocator< ::ProtoStruct::EmptyMessage, ::ProtoStruct::PPMessage>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ProtoStruct::EmptyMessage, ::ProtoStruct::PPMessage>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetPP() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPP(::grpc::ServerContext* /*context*/, const ::ProtoStruct::EmptyMessage* /*request*/, ::ProtoStruct::PPMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetPP(
      ::grpc::CallbackServerContext* /*context*/, const ::ProtoStruct::EmptyMessage* /*request*/, ::ProtoStruct::PPMessage* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetUSK : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetUSK() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::ProtoStruct::AttributeMessage, ::ProtoStruct::USKMessage>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ProtoStruct::AttributeMessage* request, ::ProtoStruct::USKMessage* response) { return this->GetUSK(context, request, response); }));}
    void SetMessageAllocatorFor_GetUSK(
        ::grpc::MessageAllocator< ::ProtoStruct::AttributeMessage, ::ProtoStruct::USKMessage>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ProtoStruct::AttributeMessage, ::ProtoStruct::USKMessage>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetUSK() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUSK(::grpc::ServerContext* /*context*/, const ::ProtoStruct::AttributeMessage* /*request*/, ::ProtoStruct::USKMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetUSK(
      ::grpc::CallbackServerContext* /*context*/, const ::ProtoStruct::AttributeMessage* /*request*/, ::ProtoStruct::USKMessage* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SetPP : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SetPP() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::ProtoStruct::PPMessage, ::ProtoStruct::EmptyMessage>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ProtoStruct::PPMessage* request, ::ProtoStruct::EmptyMessage* response) { return this->SetPP(context, request, response); }));}
    void SetMessageAllocatorFor_SetPP(
        ::grpc::MessageAllocator< ::ProtoStruct::PPMessage, ::ProtoStruct::EmptyMessage>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ProtoStruct::PPMessage, ::ProtoStruct::EmptyMessage>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SetPP() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetPP(::grpc::ServerContext* /*context*/, const ::ProtoStruct::PPMessage* /*request*/, ::ProtoStruct::EmptyMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetPP(
      ::grpc::CallbackServerContext* /*context*/, const ::ProtoStruct::PPMessage* /*request*/, ::ProtoStruct::EmptyMessage* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SetUSK : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SetUSK() {
      ::grpc::Service::MarkMethodCallback(6,
          new ::grpc::internal::CallbackUnaryHandler< ::ProtoStruct::USKMessage, ::ProtoStruct::EmptyMessage>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ProtoStruct::USKMessage* request, ::ProtoStruct::EmptyMessage* response) { return this->SetUSK(context, request, response); }));}
    void SetMessageAllocatorFor_SetUSK(
        ::grpc::MessageAllocator< ::ProtoStruct::USKMessage, ::ProtoStruct::EmptyMessage>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(6);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ProtoStruct::USKMessage, ::ProtoStruct::EmptyMessage>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SetUSK() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetUSK(::grpc::ServerContext* /*context*/, const ::ProtoStruct::USKMessage* /*request*/, ::ProtoStruct::EmptyMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetUSK(
      ::grpc::CallbackServerContext* /*context*/, const ::ProtoStruct::USKMessage* /*request*/, ::ProtoStruct::EmptyMessage* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Enc<WithCallbackMethod_EncData<WithCallbackMethod_DecData<WithCallbackMethod_GetPP<WithCallbackMethod_GetUSK<WithCallbackMethod_SetPP<WithCallbackMethod_SetUSK<Service > > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Enc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Enc() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Enc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Enc(::grpc::ServerContext* /*context*/, const ::ProtoStruct::Element* /*request*/, ::ProtoStruct::Element* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_EncData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_EncData() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_EncData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EncData(::grpc::ServerContext* /*context*/, const ::ProtoStruct::DataMessage* /*request*/, ::ProtoStruct::CTMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DecData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DecData() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_DecData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DecData(::grpc::ServerContext* /*context*/, const ::ProtoStruct::CTMessage* /*request*/, ::ProtoStruct::DataMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetPP : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetPP() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_GetPP() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPP(::grpc::ServerContext* /*context*/, const ::ProtoStruct::EmptyMessage* /*request*/, ::ProtoStruct::PPMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetUSK : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetUSK() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_GetUSK() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUSK(::grpc::ServerContext* /*context*/, const ::ProtoStruct::AttributeMessage* /*request*/, ::ProtoStruct::USKMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SetPP : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetPP() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_SetPP() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetPP(::grpc::ServerContext* /*context*/, const ::ProtoStruct::PPMessage* /*request*/, ::ProtoStruct::EmptyMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SetUSK : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetUSK() {
      ::grpc::Service::MarkMethodGeneric(6);
    }
    ~WithGenericMethod_SetUSK() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetUSK(::grpc::ServerContext* /*context*/, const ::ProtoStruct::USKMessage* /*request*/, ::ProtoStruct::EmptyMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Enc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Enc() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Enc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Enc(::grpc::ServerContext* /*context*/, const ::ProtoStruct::Element* /*request*/, ::ProtoStruct::Element* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEnc(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_EncData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_EncData() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_EncData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EncData(::grpc::ServerContext* /*context*/, const ::ProtoStruct::DataMessage* /*request*/, ::ProtoStruct::CTMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEncData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DecData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DecData() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_DecData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DecData(::grpc::ServerContext* /*context*/, const ::ProtoStruct::CTMessage* /*request*/, ::ProtoStruct::DataMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDecData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetPP : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetPP() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_GetPP() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPP(::grpc::ServerContext* /*context*/, const ::ProtoStruct::EmptyMessage* /*request*/, ::ProtoStruct::PPMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPP(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetUSK : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetUSK() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_GetUSK() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUSK(::grpc::ServerContext* /*context*/, const ::ProtoStruct::AttributeMessage* /*request*/, ::ProtoStruct::USKMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetUSK(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetPP : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetPP() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_SetPP() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetPP(::grpc::ServerContext* /*context*/, const ::ProtoStruct::PPMessage* /*request*/, ::ProtoStruct::EmptyMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetPP(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetUSK : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetUSK() {
      ::grpc::Service::MarkMethodRaw(6);
    }
    ~WithRawMethod_SetUSK() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetUSK(::grpc::ServerContext* /*context*/, const ::ProtoStruct::USKMessage* /*request*/, ::ProtoStruct::EmptyMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetUSK(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Enc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Enc() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Enc(context, request, response); }));
    }
    ~WithRawCallbackMethod_Enc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Enc(::grpc::ServerContext* /*context*/, const ::ProtoStruct::Element* /*request*/, ::ProtoStruct::Element* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Enc(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_EncData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_EncData() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->EncData(context, request, response); }));
    }
    ~WithRawCallbackMethod_EncData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EncData(::grpc::ServerContext* /*context*/, const ::ProtoStruct::DataMessage* /*request*/, ::ProtoStruct::CTMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* EncData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DecData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DecData() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DecData(context, request, response); }));
    }
    ~WithRawCallbackMethod_DecData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DecData(::grpc::ServerContext* /*context*/, const ::ProtoStruct::CTMessage* /*request*/, ::ProtoStruct::DataMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DecData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetPP : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetPP() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetPP(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetPP() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPP(::grpc::ServerContext* /*context*/, const ::ProtoStruct::EmptyMessage* /*request*/, ::ProtoStruct::PPMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetPP(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetUSK : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetUSK() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetUSK(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetUSK() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUSK(::grpc::ServerContext* /*context*/, const ::ProtoStruct::AttributeMessage* /*request*/, ::ProtoStruct::USKMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetUSK(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SetPP : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SetPP() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetPP(context, request, response); }));
    }
    ~WithRawCallbackMethod_SetPP() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetPP(::grpc::ServerContext* /*context*/, const ::ProtoStruct::PPMessage* /*request*/, ::ProtoStruct::EmptyMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetPP(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SetUSK : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SetUSK() {
      ::grpc::Service::MarkMethodRawCallback(6,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetUSK(context, request, response); }));
    }
    ~WithRawCallbackMethod_SetUSK() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetUSK(::grpc::ServerContext* /*context*/, const ::ProtoStruct::USKMessage* /*request*/, ::ProtoStruct::EmptyMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetUSK(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Enc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Enc() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ProtoStruct::Element, ::ProtoStruct::Element>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ProtoStruct::Element, ::ProtoStruct::Element>* streamer) {
                       return this->StreamedEnc(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Enc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Enc(::grpc::ServerContext* /*context*/, const ::ProtoStruct::Element* /*request*/, ::ProtoStruct::Element* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedEnc(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ProtoStruct::Element,::ProtoStruct::Element>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_EncData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_EncData() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ProtoStruct::DataMessage, ::ProtoStruct::CTMessage>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ProtoStruct::DataMessage, ::ProtoStruct::CTMessage>* streamer) {
                       return this->StreamedEncData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_EncData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status EncData(::grpc::ServerContext* /*context*/, const ::ProtoStruct::DataMessage* /*request*/, ::ProtoStruct::CTMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedEncData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ProtoStruct::DataMessage,::ProtoStruct::CTMessage>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DecData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DecData() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ProtoStruct::CTMessage, ::ProtoStruct::DataMessage>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ProtoStruct::CTMessage, ::ProtoStruct::DataMessage>* streamer) {
                       return this->StreamedDecData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DecData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DecData(::grpc::ServerContext* /*context*/, const ::ProtoStruct::CTMessage* /*request*/, ::ProtoStruct::DataMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDecData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ProtoStruct::CTMessage,::ProtoStruct::DataMessage>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetPP : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetPP() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ProtoStruct::EmptyMessage, ::ProtoStruct::PPMessage>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ProtoStruct::EmptyMessage, ::ProtoStruct::PPMessage>* streamer) {
                       return this->StreamedGetPP(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetPP() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetPP(::grpc::ServerContext* /*context*/, const ::ProtoStruct::EmptyMessage* /*request*/, ::ProtoStruct::PPMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetPP(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ProtoStruct::EmptyMessage,::ProtoStruct::PPMessage>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetUSK : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetUSK() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ProtoStruct::AttributeMessage, ::ProtoStruct::USKMessage>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ProtoStruct::AttributeMessage, ::ProtoStruct::USKMessage>* streamer) {
                       return this->StreamedGetUSK(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetUSK() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetUSK(::grpc::ServerContext* /*context*/, const ::ProtoStruct::AttributeMessage* /*request*/, ::ProtoStruct::USKMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetUSK(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ProtoStruct::AttributeMessage,::ProtoStruct::USKMessage>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetPP : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetPP() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ProtoStruct::PPMessage, ::ProtoStruct::EmptyMessage>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ProtoStruct::PPMessage, ::ProtoStruct::EmptyMessage>* streamer) {
                       return this->StreamedSetPP(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetPP() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetPP(::grpc::ServerContext* /*context*/, const ::ProtoStruct::PPMessage* /*request*/, ::ProtoStruct::EmptyMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetPP(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ProtoStruct::PPMessage,::ProtoStruct::EmptyMessage>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetUSK : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetUSK() {
      ::grpc::Service::MarkMethodStreamed(6,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ProtoStruct::USKMessage, ::ProtoStruct::EmptyMessage>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ProtoStruct::USKMessage, ::ProtoStruct::EmptyMessage>* streamer) {
                       return this->StreamedSetUSK(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetUSK() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetUSK(::grpc::ServerContext* /*context*/, const ::ProtoStruct::USKMessage* /*request*/, ::ProtoStruct::EmptyMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetUSK(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ProtoStruct::USKMessage,::ProtoStruct::EmptyMessage>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Enc<WithStreamedUnaryMethod_EncData<WithStreamedUnaryMethod_DecData<WithStreamedUnaryMethod_GetPP<WithStreamedUnaryMethod_GetUSK<WithStreamedUnaryMethod_SetPP<WithStreamedUnaryMethod_SetUSK<Service > > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Enc<WithStreamedUnaryMethod_EncData<WithStreamedUnaryMethod_DecData<WithStreamedUnaryMethod_GetPP<WithStreamedUnaryMethod_GetUSK<WithStreamedUnaryMethod_SetPP<WithStreamedUnaryMethod_SetUSK<Service > > > > > > > StreamedService;
};

}  // namespace ProtoStruct


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_Service_2eproto__INCLUDED
